### train configuraton
exp_dir: exp/WavLM-BasePlus-FullFineTuning-MHFA-emb512
gpus: "[0,1,2,3,4,5,6,7]"
num_avg: 2
enable_amp: False # whether enable automatic mixed precision training

seed: 716
num_epochs: 10
save_epoch_interval: 1 # save model every 5 epochs
log_batch_interval: 100 # log every 100 batchs

dataloader_args:
  batch_size: 128
  num_workers: 4
  pin_memory: False
  prefetch_factor: 8
  drop_last: True

dataset_args:
  # the sample number which will be traversed within one epoch, if the value equals to 0,
  # the utterance number in the dataset will be used as the sample_num_per_epoch.
  sample_num_per_epoch: 0
  shuffle: True
  shuffle_args:
    shuffle_size: 2500
  filter: True
  filter_args:
    min_num_frames: 100
    max_num_frames: 800
  resample_rate: 16000
  speed_perturb: False
  num_frms: 300
  aug_prob: 0.6 # prob to add reverb & noise aug per sample
  fbank_args:
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 1.0
  spec_aug: False
  spec_aug_args:
    num_t_mask: 1
    num_f_mask: 1
    max_t: 10
    max_f: 8
    prob: 0.6
  frontend: "wavlm"
  wavlm_args:
    frame_shift: 10

model: WavLM_MHFA
model_init: null
model_args:
  model_path: '/mnt/matylda6/pengjy/share_ssl/WavLM-Base+.pt'
  head_nb: 64
  embed_dim: 256
  pooling: "MHFA" 
  group: 1
  cnn_scale: 1.0
  layer_drop: 0.05 
  feature_grad_mult: 0.1 

projection_args:
  project_type: "arc_margin_intertopk_subcenter" # add_margin, arc_margin, sphere, softmax
  scale: 32.0
  easy_margin: False

margin_scheduler: MarginScheduler
margin_update:
  initial_margin: 0.2
  final_margin: 0.2
  increase_start_epoch: 1
  fix_start_epoch: 1
  update_margin: True
  increase_type: "exp" # exp, linear

loss: CrossEntropyLoss
loss_args: {}

optimizer: AdamW
optimizer_args:
  # momentum: 0.9
  # nesterov: True
  weight_decay: 1.0e-7

scheduler: ExponentialDecrease
scheduler_args:
  initial_lr: 1.0e-4 # 8.0e-3
  final_lr: 1.0e-6 #4.4e-3 
  warm_up_epoch: 2
  warm_from_zero: True
